### ISSUE TITLE
3.0 Feature Element (Hero)

### ISSUE THREAD

**Issue by peareye** [wolfmoritz/ppfr#23]
Home Page

The Feature element on the home page should show the most recent recipe image. The Recipe Title and Recipe Subtitle should also appear.  _At some point there may also be a small blurb about the recipe limited to so much text (with ellipsis')_. There should be a link to the recipe via CTA button.

Recipe Page
Linking to a recipe should show the recipe image in the Feature element area. If there is no image, just show title/subtitle. The background will suffice as an image.  There is no CTA button on a recipe page.

_feature.html

**Comment by wolfmoritz** [comment]
Done!
