### ISSUE TITLE
3.0 Home Page Layout

### ISSUE THREAD

**Issue by peareye** [wolfmoritz/ppfr#24]
The home page will be made up of:

1. Feature Element (Latest Recipe)
2. Latest Recipes (to be determined number of cards) with a link to see more that links to the recipes in order of date (newest first).
3. Most Popular recipes (number of cards, see #2) with a link to see more that links to the recipes in order of popularity.
4. Random Recipe  (?) not sure about this one if it is necessary or not (number of cards, see #2). No link to random.
5. Blog posts (?) not sure about this one if it is necessary or not (number of cards, see #2). Link to all blog posts.

**Comment by wolfmoritz** [comment]
Think this complete.
