### ISSUE TITLE
Recipe Owner

### ISSUE THREAD

**Issue by peareye** [wolfmoritz/ppfr#25]
The name of the owner of the recipe in the sidebar has disappeared again. Not sure if it is something I did.
<img width="372" alt="Screenshot 2020-01-28 at 09 38 56" src="https://user-images.githubusercontent.com/11490640/73252065-06a9d900-41b2-11ea-8036-5b3149871c22.png">

**Comment by wolfmoritz** [comment]
My bad, something I did last night.

**Comment by wolfmoritz** [comment]
Resolved issue with default query getRecipe() and getUser();	68682a8	Wolfgang Moritz <wolfmoritz@gmail.com>	Jan 28, 2020 at 8:41 PM
